services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  mongo_container:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
volumes:
  db_data: